"""empty message

Revision ID: 06908ebed21c
Revises: 39ae78fcd073
Create Date: 2022-07-25 17:39:21.040411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06908ebed21c'
down_revision = '39ae78fcd073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_tags', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('task_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_tags', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('task_tags', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('task_tags', 'id')
    # ### end Alembic commands ###
