"""empty message

Revision ID: 5dff18dad2a1
Revises: 54bf6ae773a4
Create Date: 2022-07-24 11:29:05.578644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dff18dad2a1'
down_revision = '54bf6ae773a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('taskerId', sa.Integer(), nullable=False),
    sa.Column('taskId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('reviews_poster_id_fkey', 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'poster_id')
    op.drop_constraint('tasks_tasker_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'completed')
    op.drop_column('tasks', 'tasker_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tasker_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('tasks_tasker_id_fkey', 'tasks', 'users', ['tasker_id'], ['id'])
    op.add_column('reviews', sa.Column('poster_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('reviews_poster_id_fkey', 'reviews', 'users', ['poster_id'], ['id'])
    op.drop_table('bookings')
    # ### end Alembic commands ###
