"""empty message

Revision ID: ed4e342f2ac2
Revises: 153c7a6fb42d
Create Date: 2022-07-24 11:37:04.545200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4e342f2ac2'
down_revision = '153c7a6fb42d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('tasker_id', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('task_id', sa.Integer(), nullable=False))
    op.drop_constraint('bookings_taskerId_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_taskId_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['tasker_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'tasks', ['task_id'], ['id'])
    op.drop_column('bookings', 'taskerId')
    op.drop_column('bookings', 'taskId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('taskId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('taskerId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_taskId_fkey', 'bookings', 'tasks', ['taskId'], ['id'])
    op.create_foreign_key('bookings_taskerId_fkey', 'bookings', 'users', ['taskerId'], ['id'])
    op.drop_column('bookings', 'task_id')
    op.drop_column('bookings', 'tasker_id')
    # ### end Alembic commands ###
