"""empty message

Revision ID: 153c7a6fb42d
Revises: 5dff18dad2a1
Create Date: 2022-07-24 11:31:43.514332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153c7a6fb42d'
down_revision = '5dff18dad2a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bookings', 'tasks', ['taskId'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['taskerId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    # ### end Alembic commands ###
