"""empty message

Revision ID: 39ae78fcd073
Revises: ed4e342f2ac2
Create Date: 2022-07-24 11:38:26.755153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ae78fcd073'
down_revision = 'ed4e342f2ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_tags', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.add_column('task_tags', sa.Column('task_id', sa.Integer(), nullable=False))
    op.drop_constraint('task_tags_tagId_fkey', 'task_tags', type_='foreignkey')
    op.drop_constraint('task_tags_taskId_fkey', 'task_tags', type_='foreignkey')
    op.create_foreign_key(None, 'task_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'task_tags', 'tasks', ['task_id'], ['id'])
    op.drop_column('task_tags', 'tagId')
    op.drop_column('task_tags', 'taskId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_tags', sa.Column('taskId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task_tags', sa.Column('tagId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task_tags', type_='foreignkey')
    op.drop_constraint(None, 'task_tags', type_='foreignkey')
    op.create_foreign_key('task_tags_taskId_fkey', 'task_tags', 'tasks', ['taskId'], ['id'])
    op.create_foreign_key('task_tags_tagId_fkey', 'task_tags', 'tags', ['tagId'], ['id'])
    op.drop_column('task_tags', 'task_id')
    op.drop_column('task_tags', 'tag_id')
    # ### end Alembic commands ###
