"""edited nullability on user columns

Revision ID: 1db6181f29a0
Revises: 6ccd66cf46bf
Create Date: 2022-07-22 10:18:11.370878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db6181f29a0'
down_revision = '6ccd66cf46bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
